### ISSUE TITLE
Sidebars on our pages

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#89] opened 2016-11-29 20:24 UTC
Hi guys!

Eva has asked me to streamline our pages without having to go through the massive job of doing a total site overhaul. :)

She sent me to a different race site that she'd like for me to use as a guide for our event pages. The main difference (other than ours have a lot more written content that I'll be paring down) is that they use sidebars.

I poked around online and it appears that sidebars can be added to existing themes. I found a Wordpress  tutorial on how to do it. Apparently "most simple WordPress templates/themes generally employ a single sidebar. But, in keeping with WordPress' open architecture, you can easily add a second (or 3rd or 4th) sidebar to your site's theme." It goes on about registering the sidebar within the template by making an entry in the template's functions.php file, creating a separate, custom sidebar called sidebar-homepage.php, including a reference to our custom sidebar-homepage.php in our custom page template, and that's all the steps to have a 2nd sidebar on the homepage.

None of which I've really given much thought on HOW. I'm sure I could figure it out. I hope.

What I need is to be able to have sidebars on both the event template and the full-width page. Ideally, I would be able to add color backgrounds and borders to the sidebars to further distinguish them from the rest of the page's content.

So... how can we get this done?

**Comment by brashrebel** [comment] 2016-11-30 13:25
@AnaHotaling I'm flying out to Philly for a conference today and will be back next week. We might have to discuss this further. Nice job doing so much research and coming up with a potentially creative solution. I look forward to working together on it.

**Comment by AnaHotaling** [comment] 2016-12-09 18:26
Thanks! Hopefully soon... Eva wants me to streamline our page ASAP and this will help!

**Comment by brashrebel** [comment] 2016-12-09 19:47
Eva and I just had a discussion and agreed that there are likely better ways for us to streamline than adding sidebars to these templates. They do not exist there currently by design and not due to any technical limitation. We determined that these kinds of pages are not well suited for sidebar, multi column layouts.

That said, there are still other potential options to explore for improving the layout. Discussion should continue.

**Comment by AnaHotaling** [comment] 2016-12-09 19:53
Agreed. I was going to sketch something out on the computer but then a) I
figured it would make the mobile version AWFUL and b) I got sick. So I'll
lie here and think some more. Did Eva provide you with the link for the
page she'd looked at as an example of how to streamline? It's
http://www.theturkeytrot.com.

**Comment by brashrebel** [comment] 2016-12-20 18:05
Yeah, that site's a bit more streamlined. But you guys have like fifty times more information so I just don't think their layout will work for you as well as it does for them.

**Comment by AnaHotaling** [comment] 2016-12-20 22:05
Right... but one of my to-dos is to cut back and streamline the site so
it's pretty much just the facts, right in people's faces so they don't have
to scroll and so they don't have too much to read... without a new theme or
major redesign. That's why I thought sidebars would do it.

**Comment by BigActual** [comment] 2018-09-18 16:53
Addressed in theme

**Closed as completed by BigActual** 2018-09-18 16:53 UTC
